#!/bin/bash
#This script is ugly, feel free to fix it

if [ "$#" -ne 2 ]; then
    echo "usage ./cmd target-rootfs path-to-target-toolchain-compiler"
    exit -1
fi

#passed args
ROOTFS=$1
TOOLCHAIN=$2

if [ -x $TOOLCHAIN ]; then
    echo "Passed valid toolchain"
    MACHINE=$($TOOLCHAIN -dumpmachine)
    DEB_MULTI_ARCH_MADNESS=$ROOTFS/usr/lib/$MACHINE
fi

INITIAL_DIR=$PWD

function adjustSymLinks
{
    echo "Adjusting the symlinks in $1 to be relative"
    cd $1

    ls -la | grep -E "^l.*?-> \/" | while read i;
    do
    file=$(echo "$i" | awk '{print $9}')
    relativePath=$(echo "$i" | awk '{print $11}' | sed -e "s,\(.*\),$2\1,g")
    echo "$file -> $relativePath"
    sudo rm $file
    sudo ln -s $relativePath $file
    done

    cd $INITIAL_DIR
}

adjustSymLinks $ROOTFS/usr/lib "../.."

echo "Testing for existence of potential debian multi-arch dir: $DEB_MULTI_ARCH_MADNESS"

if [ -n "$DEB_MULTI_ARCH_MADNESS" -a -e "$DEB_MULTI_ARCH_MADNESS" ]; then
    echo "Debian multiarch dir exists, adjusting"
    adjustSymLinks $DEB_MULTI_ARCH_MADNESS "../../.."
fi
